AWSTemplateFormatVersion: "2010-09-09"
Description: create an s3 bucket for hosting static website
Parameters:
  BucketName:
    Type: String
    Default: premiumproductonline.com
  BucketNameWWW:
    Type: String
    Default: www.premiumproductonline.com
Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
        IgnorePublicAcls: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
        RoutingRules:
          - RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: "403"
            RedirectRule:
              HostName: !Ref BucketName
              ReplaceKeyPrefixWith: "#!/"
  s3BucketWWW:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameWWW
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
        IgnorePublicAcls: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
        RoutingRules:
          - RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: "403"
            RedirectRule:
              HostName: !Ref BucketName
              ReplaceKeyPrefixWith: "#!/"
  SomeS3AccessPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: s3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${BucketName}/*
  SomeS3AccessPolicyWWW:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: s3BucketWWW
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${BucketNameWWW}/*